[package]
name = "bigtent"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
regex = "1.10.4"
md5 = "0.7.0"
sha2 = "0.10.8"
# boring = "4.7.0"
hex = "0.4.3"
bytes = "1.6.0"
hex-literal = "0.4.1"
shellexpand = "3.1.0"
chrono = "0.4.38"

# Web Framework stuff
rouille = "3.6.2"
url = "2.5.0"
serde = {version = "1.0.202", features = ["std", "derive"]}
serde_json = "1.0.117"
serde_cbor = "0.11.2"

im = {version = "15.1.0", features = ["serde"]}
# tracing = "0.1.40"
# tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}


# Execution stuff
signal-hook = "0.3.17"
arc-swap = "1.7.1"
clap = { version = "4.5.4", features = ["derive"] }
toml = "0.8.13"
thousands = "0.2.0"
pipe = "0.4.0"

flume = {version = "0.11.0", features = ["spin"]}
scopeguard = "1.2.0"

rand = "0.8.5"

# Logging
log = "0.4.21"
env_logger = "0.11.3"

[features]

longtest = [] # feature has no explicit dependencies
oldstuff = []