
name: Rust Build & Test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types: 
      - "published"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo test --verbose --lib
    - name: Record Check Status
      run: |
        curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -F 'name=Tests' \
          -F 'head_sha=${{ github.event.pull_request.head.sha }}' \
          -F 'status=complete' \
          -F 'output[title]=Tests pass' \
          https://api.github.com/repos/${{ github.repository }}/check-runs \
